version: "3.9"

services:
  database_school:
    image: postgres
    container_name: database_school
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=school
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=passw
    volumes:
      - pgdata:/data/postgres
 
  redis:
    image: redis
    container_name: redis_school
    restart: always
    ports:
      - 6379:6379
  app:
    build: .
    container_name: school_api
    restart: always
    ports:
      - 3003:3003
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database_school
      - redis_school
    depends_on:
      - database_school
      - redis_school
volumes:
  pgdata:
    driver: local
